/**
 * Données de test réalistes pour le tableau de bord Super Admin
 */

import { EntrepriseCliente, StatsSuperAdmin } from "./types";

export const STATS_SUPER_ADMIN_MOCK: StatsSuperAdmin = {
  totalEntreprises: 48,
  entreprisesActives: 34,
  entreprisesEssai: 10,
  entreprisesImpayees: 4,
  mrrFcfa: 4680000,
  arrFcfa: 56160000,
  totalChantiersPlateforme: 186,
  totalUtilisateursPlateforme: 412,
  tauxConversionEssai: 76.5,
};

export const ENTREPRISES_CLIENTES_MOCK: EntrepriseCliente[] = [
  {
    id: "ent-001",
    raisonSociale: "SOUMAFE BTP & Construction Sarl",
    nomCommercial: "SOUMAFE SARL",
    pays: "Côte d'Ivoire",
    ville: "Abidjan (Cocody)",
    dateInscription: "2026-03-12",
    contactNom: "Ibrahim Soumahoro",
    contactEmail: "direction@soumafe-btp.ci",
    contactTel: "+225 07 48 92 10 33",
    planActuel: {
      code: "MAITRE_OEUVRE",
      libelle: "Maître d'Œuvre",
      cycle: "ANNUEL",
      montantFcfa: 790000,
    },
    statut: "ACTIF",
    prochaineEcheance: "2027-03-12",
    nombreChantiers: 14,
    nombreUtilisateurs: 22,
    stockageUtiliseMo: 8400,
    derniereConnexion: "Aujourd'hui à 14:15",
    derniereFactureRef: "FAC-2026-0182",
  },
  {
    id: "ent-002",
    raisonSociale: "Groupe Bâtir Afrique SA",
    nomCommercial: "BÂTIR AFRIQUE",
    pays: "Sénégal",
    ville: "Dakar (Almadies)",
    dateInscription: "2026-01-20",
    contactNom: "Abdoulaye Diallo",
    contactEmail: "a.diallo@batirafrique.sn",
    contactTel: "+221 77 654 32 10",
    planActuel: {
      code: "PROMOTEUR",
      libelle: "Promoteur",
      cycle: "ANNUEL",
      montantFcfa: 1890000,
    },
    statut: "ACTIF",
    prochaineEcheance: "2027-01-20",
    nombreChantiers: 38,
    nombreUtilisateurs: 64,
    stockageUtiliseMo: 42300,
    derniereConnexion: "Hier à 18:30",
    derniereFactureRef: "FAC-2026-0094",
  },
  {
    id: "ent-003",
    raisonSociale: "Ivoire Génie Civil & Bâtiment",
    nomCommercial: "IGCB CI",
    pays: "Côte d'Ivoire",
    ville: "Yopougon, Abidjan",
    dateInscription: "2026-09-08",
    contactNom: "Serge Kouamé",
    contactEmail: "s.kouame@igcb-ci.com",
    contactTel: "+225 05 12 34 56 78",
    planActuel: {
      code: "MAITRE_OEUVRE",
      libelle: "Maître d'Œuvre (Essai)",
      cycle: "MENSUEL",
      montantFcfa: 79000,
    },
    statut: "ESSAI",
    joursEssaiRestants: 6,
    prochaineEcheance: "2026-09-22",
    nombreChantiers: 3,
    nombreUtilisateurs: 5,
    stockageUtiliseMo: 1100,
    derniereConnexion: "Aujourd'hui à 11:20",
  },
  {
    id: "ent-004",
    raisonSociale: "Atelier d'Architecture & Travaux Moderne",
    nomCommercial: "ARCHI-MODERNE",
    pays: "Burkina Faso",
    ville: "Ouagadougou",
    dateInscription: "2026-06-15",
    contactNom: "Salif Ouedraogo",
    contactEmail: "contact@archi-moderne.bf",
    contactTel: "+226 70 88 99 00",
    planActuel: {
      code: "BATISSEUR",
      libelle: "Bâtisseur",
      cycle: "MENSUEL",
      montantFcfa: 29000,
    },
    statut: "ACTIF",
    prochaineEcheance: "2026-10-15",
    nombreChantiers: 4,
    nombreUtilisateurs: 4,
    stockageUtiliseMo: 2800,
    derniereConnexion: "Il y a 3 jours",
    derniereFactureRef: "FAC-2026-0312",
  },
  {
    id: "ent-005",
    raisonSociale: "Générale des Travaux Publics Mali",
    nomCommercial: "GTP MALI",
    pays: "Mali",
    ville: "Bamako",
    dateInscription: "2026-04-02",
    contactNom: "Moussa Konaté",
    contactEmail: "m.konate@gtp-mali.ml",
    contactTel: "+223 66 77 88 99",
    planActuel: {
      code: "PROMOTEUR",
      libelle: "Promoteur",
      cycle: "MENSUEL",
      montantFcfa: 189000,
    },
    statut: "IMPAYE",
    prochaineEcheance: "2026-09-02 (En retard)",
    nombreChantiers: 12,
    nombreUtilisateurs: 28,
    stockageUtiliseMo: 18400,
    derniereConnexion: "Il y a 5 jours",
    derniereFactureRef: "FAC-2026-0275",
  },
  {
    id: "ent-006",
    raisonSociale: "Bénin Travaux & Équipements",
    nomCommercial: "BTE Cotonou",
    pays: "Bénin",
    ville: "Cotonou",
    dateInscription: "2026-09-12",
    contactNom: "Gilles Dossou",
    contactEmail: "gilles@bte-benin.bj",
    contactTel: "+229 97 11 22 33",
    planActuel: {
      code: "MAITRE_OEUVRE",
      libelle: "Maître d'Œuvre (Essai)",
      cycle: "MENSUEL",
      montantFcfa: 79000,
    },
    statut: "ESSAI",
    joursEssaiRestants: 10,
    prochaineEcheance: "2026-09-26",
    nombreChantiers: 2,
    nombreUtilisateurs: 4,
    stockageUtiliseMo: 650,
    derniereConnexion: "Aujourd'hui à 09:40",
  },
  {
    id: "ent-007",
    raisonSociale: "Compagnie Africaine de Bâtiment",
    nomCommercial: "CABAT Togo",
    pays: "Togo",
    ville: "Lomé",
    dateInscription: "2025-11-10",
    contactNom: "Koffi Lawson",
    contactEmail: "klawson@cabat.tg",
    contactTel: "+228 90 44 55 66",
    planActuel: {
      code: "MAITRE_OEUVRE",
      libelle: "Maître d'Œuvre",
      cycle: "MENSUEL",
      montantFcfa: 79000,
    },
    statut: "SUSPENDU",
    prochaineEcheance: "Suspendu le 15/08/2026",
    nombreChantiers: 8,
    nombreUtilisateurs: 15,
    stockageUtiliseMo: 11200,
    derniereConnexion: "Il y a 32 jours",
    derniereFactureRef: "FAC-2026-0220",
  },
  {
    id: "ent-008",
    raisonSociale: "Société des Travaux d'Assainissement du Gabon",
    nomCommercial: "STAG BTP",
    pays: "Gabon",
    ville: "Libreville",
    dateInscription: "2026-02-18",
    contactNom: "Armel Ondo",
    contactEmail: "direction@stag-btp.ga",
    contactTel: "+241 07 22 33 44",
    planActuel: {
      code: "BATISSEUR",
      libelle: "Bâtisseur",
      cycle: "ANNUEL",
      montantFcfa: 290000,
    },
    statut: "ACTIF",
    prochaineEcheance: "2027-02-18",
    nombreChantiers: 5,
    nombreUtilisateurs: 5,
    stockageUtiliseMo: 3100,
    derniereConnexion: "Hier à 15:10",
    derniereFactureRef: "FAC-2026-0112",
  },
];
