/**
 * Données de test pour le suivi d'avancement des chantiers et photos de preuve
 */

import { PhotoPreuve, ProjetAvancement } from "./types";

export const PHOTOS_PREUVES_INITIAL: PhotoPreuve[] = [
  {
    id: "photo-01",
    url: "https://images.unsplash.com/photo-1541888946425-d0fbb186156a?auto=format&fit=crop&w=800&q=80",
    titre: "Ferraillage de la dalle haute et réservations R+2",
    lotId: "lot-01",
    nomLot: "Gros Œuvre & Structure",
    datePrise: "2026-09-16 11:30",
    auteurNom: "Mamadou Traoré",
    auteurRole: "Chef de Chantier",
    localisation: "Zone Bâtiment B - Trame Nord",
    pourcentageAssocie: 85,
    statutConformite: "VERIFIEE",
    commentaire: "Espacement des barres conforme aux plans BA. Calage d'enrobage 3cm vérifié.",
  },
  {
    id: "photo-02",
    url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
    titre: "Coulage des poteaux d'angle P3 et P4",
    lotId: "lot-01",
    nomLot: "Gros Œuvre & Structure",
    datePrise: "2026-09-15 16:45",
    auteurNom: "Mamadou Traoré",
    auteurRole: "Chef de Chantier",
    localisation: "Angle Nord-Est",
    pourcentageAssocie: 80,
    statutConformite: "VERIFIEE",
    commentaire: "Vibration du béton satisfaisante, aucun nid de gravier après décoffrage partiel.",
  },
  {
    id: "photo-03",
    url: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    titre: "Passage des gaines électriques ICTA sous dalle",
    lotId: "lot-02",
    nomLot: "Électricité & Courants Faibles",
    datePrise: "2026-09-14 14:10",
    auteurNom: "Bakary Diarra",
    auteurRole: "Électricien Chef d'Équipe",
    localisation: "Étage R+1, Appartement 102",
    pourcentageAssocie: 45,
    statutConformite: "VERIFIEE",
    commentaire: "Gaines repérées et fixées avant coulage de la chape.",
  },
  {
    id: "photo-04",
    url: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=800&q=80",
    titre: "Pose des colonnes montantes EU/EV",
    lotId: "lot-03",
    nomLot: "Plomberie & Sanitaires",
    datePrise: "2026-09-12 10:20",
    auteurNom: "Adama Soro",
    auteurRole: "Plombier Sanibay",
    localisation: "Gaine technique centrale",
    pourcentageAssocie: 30,
    statutConformite: "EN_ATTENTE",
    commentaire: "Raccordement des culottes PVC en attente de test d'étanchéité.",
  },
];

export const PROJETS_AVANCEMENT_MOCK: ProjetAvancement[] = [
  {
    id: "proj-001",
    code: "PALM-B",
    nom: "Résidence Les Palmiers - Bâtiment B",
    clientMOA: "Société Immobilière de la Lagune (SIL)",
    localisation: "Cocody Riviera Golf, Abidjan",
    dateDebut: "2026-01-15",
    dateFinPrevue: "2026-12-20",
    avancementReelGlobal: 68,
    avancementTheoriqueGlobal: 65,
    lots: [
      {
        id: "lot-01",
        numeroLot: "01",
        nom: "Gros Œuvre & Structure Béton Armé",
        responsableNom: "Mamadou Traoré",
        avancementReel: 85,
        avancementTheorique: 80,
        sousTaches: [
          { id: "st-1", libelle: "Fondations profondes & Longrines", poidsPourcentage: 20, avancement: 100 },
          { id: "st-2", libelle: "Poteaux et poutres RDC à R+1", poidsPourcentage: 25, avancement: 100 },
          { id: "st-3", libelle: "Dalle haute R+1", poidsPourcentage: 25, avancement: 100 },
          { id: "st-4", libelle: "Poteaux et voiles R+2", poidsPourcentage: 20, avancement: 70 },
          { id: "st-5", libelle: "Coffrage et plancher R+3", poidsPourcentage: 10, avancement: 30 },
        ],
        photosPreuvesIds: ["photo-01", "photo-02"],
      },
      {
        id: "lot-02",
        numeroLot: "02",
        nom: "Électricité & Courants Faibles",
        responsableNom: "ELECBAT Sarl",
        avancementReel: 45,
        avancementTheorique: 40,
        sousTaches: [
          { id: "st-11", libelle: "Incorporations gaines sous dalle", poidsPourcentage: 40, avancement: 80 },
          { id: "st-12", libelle: "Tirage de câbles et pieuvres", poidsPourcentage: 30, avancement: 35 },
          { id: "st-13", libelle: "Tableaux électriques et appareillages", poidsPourcentage: 30, avancement: 10 },
        ],
        photosPreuvesIds: ["photo-03"],
      },
      {
        id: "lot-03",
        numeroLot: "03",
        nom: "Plomberie & Réseaux Sanitaires",
        responsableNom: "SANIBAT CI",
        avancementReel: 30,
        avancementTheorique: 35,
        sousTaches: [
          { id: "st-21", libelle: "Passage colonnes montantes PVC", poidsPourcentage: 50, avancement: 50 },
          { id: "st-22", libelle: "Distribution eau chaude/froide multicouche", poidsPourcentage: 30, avancement: 15 },
          { id: "st-23", libelle: "Pose des sanitaires", poidsPourcentage: 20, avancement: 0 },
        ],
        photosPreuvesIds: ["photo-04"],
      },
      {
        id: "lot-04",
        numeroLot: "04",
        nom: "Menuiserie Aluminium & Vitrerie",
        responsableNom: "ALUBAT Côte d'Ivoire",
        avancementReel: 15,
        avancementTheorique: 15,
        sousTaches: [
          { id: "st-31", libelle: "Prise de cotes définitives", poidsPourcentage: 30, avancement: 100 },
          { id: "st-32", libelle: "Fabrication des précadres en atelier", poidsPourcentage: 40, avancement: 60 },
          { id: "st-33", libelle: "Pose sur site", poidsPourcentage: 30, avancement: 0 },
        ],
        photosPreuvesIds: [],
      },
    ],
    photos: PHOTOS_PREUVES_INITIAL,
  },
  {
    id: "proj-002",
    code: "TH-02",
    nom: "Tour Horizon d'Affaires - R+12",
    clientMOA: "Société Ivoirienne de Promotion (SIP)",
    localisation: "Le Plateau, Abidjan",
    dateDebut: "2025-10-01",
    dateFinPrevue: "2027-04-30",
    avancementReelGlobal: 42,
    avancementTheoriqueGlobal: 40,
    lots: [
      {
        id: "lot-101",
        numeroLot: "01",
        nom: "Fondations Spéciales & Parois Moulées",
        responsableNom: "Spie Batignolles CI",
        avancementReel: 100,
        avancementTheorique: 100,
        sousTaches: [
          { id: "st-101", libelle: "Pieux forés diamètre 1000", poidsPourcentage: 60, avancement: 100 },
          { id: "st-102", libelle: "Radier général épaisseur 1.80m", poidsPourcentage: 40, avancement: 100 },
        ],
        photosPreuvesIds: [],
      },
      {
        id: "lot-102",
        numeroLot: "02",
        nom: "Superstructure Béton Armé R+12",
        responsableNom: "SOUMAFE SARL",
        avancementReel: 52,
        avancementTheorique: 50,
        sousTaches: [
          { id: "st-111", libelle: "Noyau central ascenseurs jusqu'à R+6", poidsPourcentage: 50, avancement: 70 },
          { id: "st-112", libelle: "Planchers précontraints R+1 à R+5", poidsPourcentage: 50, avancement: 60 },
        ],
        photosPreuvesIds: [],
      },
    ],
    photos: [],
  },
];
