/**
 * Référentiel des villes des neuf pays où une entreprise peut s'inscrire.
 *
 * **Ce fichier est généré.** Sa source est
 * `backend/apps/projets/referentiels/villes.py`, où la même liste porte les
 * coordonnées GPS dont la météo a besoin. Ne pas l'éditer à la main :
 *
 *     python manage.py generer_referentiel_villes
 *
 * `test_le_referentiel_typescript_ne_derive_pas` rejoue la commande en mode
 * vérification et casse la suite si les deux listes ne disent plus la même
 * chose.
 *
 * Il est **statique** : une liste déroulante qui attend une réponse d'API est
 * une liste déroulante vide au moment où on l'ouvre.
 */

/** Le nom de l'agglomération principale, pour les pays qui en découpent une. */
export const AGGLOMERATION: Record<string, string> = {
  CI: "Abidjan",
  GN: "Conakry",
  SN: "Dakar",
};

/** Les communes de l'agglomération principale — un groupe à part dans la liste. */
export const COMMUNES_AGGLOMERATION: Record<string, string[]> = {
  CI: [
    "Abobo",
    "Adjamé",
    "Anyama",
    "Attécoubé",
    "Bingerville",
    "Cocody",
    "Koumassi",
    "Marcory",
    "Plateau",
    "Port-Bouët",
    "Songon",
    "Treichville",
    "Yopougon",
  ],
  GN: [
    "Dixinn",
    "Kaloum",
    "Matam",
    "Matoto",
    "Ratoma",
  ],
  SN: [
    "Bargny",
    "Dakar",
    "Guédiawaye",
    "Keur Massar",
    "Pikine",
    "Rufisque",
  ],
};

/** Les autres villes du pays, par ordre alphabétique. */
export const VILLES_HORS_AGGLOMERATION: Record<string, string[]> = {
  BF: [
    "Banfora",
    "Bobo-Dioulasso",
    "Boromo",
    "Diapaga",
    "Djibo",
    "Dori",
    "Dédougou",
    "Fada N'Gourma",
    "Gaoua",
    "Garango",
    "Kaya",
    "Kongoussi",
    "Koudougou",
    "Léo",
    "Manga",
    "Nouna",
    "Orodara",
    "Ouagadougou",
    "Ouahigouya",
    "Pô",
    "Réo",
    "Solenzo",
    "Tenkodogo",
    "Tougan",
    "Yako",
    "Ziniaré",
  ],
  BJ: [
    "Abomey",
    "Abomey-Calavi",
    "Allada",
    "Aplahoué",
    "Banikoara",
    "Bembèrèkè",
    "Bohicon",
    "Comè",
    "Cotonou",
    "Dassa-Zoumé",
    "Djougou",
    "Grand-Popo",
    "Kandi",
    "Kétou",
    "Lokossa",
    "Malanville",
    "Natitingou",
    "Nikki",
    "Ouidah",
    "Parakou",
    "Pobè",
    "Porto-Novo",
    "Sakété",
    "Savalou",
    "Tanguiéta",
  ],
  CI: [
    "Abengourou",
    "Aboisso",
    "Adzopé",
    "Agboville",
    "Agnibilékrou",
    "Akoupé",
    "Alépé",
    "Bondoukou",
    "Bongouanou",
    "Bonoua",
    "Bouaké",
    "Bouna",
    "Boundiali",
    "Dabou",
    "Daloa",
    "Danané",
    "Daoukro",
    "Divo",
    "Duékoué",
    "Ferkessédougou",
    "Gagnoa",
    "Grand-Bassam",
    "Guiglo",
    "Issia",
    "Jacqueville",
    "Katiola",
    "Korhogo",
    "Man",
    "Odienné",
    "Oumé",
    "San-Pédro",
    "Sassandra",
    "Sikensi",
    "Sinématiali",
    "Soubré",
    "Séguéla",
    "Tabou",
    "Tanda",
    "Tengréla",
    "Tiassalé",
    "Toumodi",
    "Vavoua",
    "Yamoussoukro",
    "Zuénoula",
  ],
  CM: [
    "Bafang",
    "Bafoussam",
    "Bamenda",
    "Batouri",
    "Bertoua",
    "Buea",
    "Douala",
    "Dschang",
    "Ebolowa",
    "Edéa",
    "Foumban",
    "Garoua",
    "Guider",
    "Kousséri",
    "Kribi",
    "Kumba",
    "Kumbo",
    "Limbe",
    "Maroua",
    "Mbalmayo",
    "Mbouda",
    "Meiganga",
    "Nanga-Eboko",
    "Ngaoundéré",
    "Nkongsamba",
    "Obala",
    "Sangmélima",
    "Tiko",
    "Wum",
    "Yagoua",
    "Yaoundé",
  ],
  GA: [
    "Akanda",
    "Bitam",
    "Booué",
    "Cocobeach",
    "Fougamou",
    "Franceville",
    "Gamba",
    "Koulamoutou",
    "Lambaréné",
    "Lastoursville",
    "Libreville",
    "Makokou",
    "Mayumba",
    "Mitzic",
    "Moanda",
    "Mouila",
    "Ndjolé",
    "Ntoum",
    "Okondja",
    "Owendo",
    "Oyem",
    "Port-Gentil",
    "Tchibanga",
  ],
  GN: [
    "Beyla",
    "Boké",
    "Coyah",
    "Dabola",
    "Dalaba",
    "Dubréka",
    "Faranah",
    "Forécariah",
    "Fria",
    "Guéckédou",
    "Kamsar",
    "Kankan",
    "Kindia",
    "Kissidougou",
    "Koundara",
    "Kérouané",
    "Labé",
    "Lola",
    "Macenta",
    "Mamou",
    "Mandiana",
    "Nzérékoré",
    "Pita",
    "Siguiri",
    "Tougué",
    "Télimélé",
  ],
  ML: [
    "Ansongo",
    "Bafoulabé",
    "Bamako",
    "Bandiagara",
    "Bla",
    "Bougouni",
    "Dioïla",
    "Djenné",
    "Douentza",
    "Gao",
    "Kati",
    "Kayes",
    "Kidal",
    "Kita",
    "Kolokani",
    "Koulikoro",
    "Koutiala",
    "Markala",
    "Mopti",
    "Niono",
    "Nioro du Sahel",
    "San",
    "Sikasso",
    "Ségou",
    "Sévaré",
    "Tombouctou",
    "Yanfolila",
  ],
  SN: [
    "Bignona",
    "Dahra",
    "Diourbel",
    "Fatick",
    "Foundiougne",
    "Kaffrine",
    "Kaolack",
    "Kolda",
    "Kédougou",
    "Linguère",
    "Louga",
    "Matam",
    "Mbacké",
    "Mbour",
    "Nioro du Rip",
    "Podor",
    "Richard-Toll",
    "Saint-Louis",
    "Sédhiou",
    "Tambacounda",
    "Thiès",
    "Tivaouane",
    "Touba",
    "Vélingara",
    "Ziguinchor",
  ],
  TG: [
    "Amlamé",
    "Aného",
    "Atakpamé",
    "Badou",
    "Bassar",
    "Blitta",
    "Dapaong",
    "Kandé",
    "Kara",
    "Kpalimé",
    "Lomé",
    "Mango",
    "Niamtougou",
    "Notsé",
    "Sokodé",
    "Sotouboua",
    "Tabligbo",
    "Tchamba",
    "Tsévié",
    "Vogan",
  ],
};

export interface ListeVilles {
  /** Le nom de l'agglomération, vide quand le pays n'en découpe pas. */
  agglomeration: string;
  /** Les communes de cette agglomération — vide dans le même cas. */
  communes: string[];
  /** Toutes les autres villes du pays. */
  autres: string[];
}

/**
 * Les villes d'un pays, prêtes à grouper.
 *
 * Un pays sans référentiel renvoie trois listes vides : l'écran bascule alors
 * sur sa saisie libre, ce qui est le comportement voulu — mieux vaut un champ
 * texte qu'une liste déroulante vide.
 */
export function listerVilles(pays: string): ListeVilles {
  const code = (pays || "").trim().toUpperCase();
  return {
    agglomeration: AGGLOMERATION[code] ?? "",
    communes: COMMUNES_AGGLOMERATION[code] ?? [],
    autres: VILLES_HORS_AGGLOMERATION[code] ?? [],
  };
}

/** La ville figure-t-elle au référentiel de ce pays. */
export function villeConnue(pays: string, nom: string): boolean {
  if (!nom) return false;
  const { communes, autres } = listerVilles(pays);
  return communes.includes(nom) || autres.includes(nom);
}
